apiVersion: batch/v1
kind: CronJob
metadata:
  name: minute-backup
  namespace: nginx
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: minute-backup
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-container
              image: busybox
              command:
                - sh
                - -c
                - |
                  echo "Backup Started";
                  mkdir -p /backups /demo-data;
                  cp -r /demo-data/* /backups/ || true;
                  echo "Backup Completed";
              volumeMounts:
                - name: data-volume
                  mountPath: /demo-data
                - name: backup-volume
                  mountPath: /backups
          volumes:
            - name: data-volume
              hostPath:
                path: /demo-data
                type: DirectoryOrCreate
            - name: backup-volume
              hostPath:
                path: /backups
                type: DirectoryOrCreate
